create or replace
FUNCTION ISMATIERE(CODEMAT IN VARCHAR2)
                  RETURN NUMBER AS
COUNT_MAT NUMBER;
BEGIN
  SELECT COUNT(CODE) INTO COUNT_MAT
  FROM MODULE
  WHERE CODE=CODEMAT
  AND CODE NOT IN (SELECT CODEPERE
                   FROM MODULE
                   WHERE CODEPERE IS NOT NULL);
  
  IF COUNT_MAT = 0 THEN
    RETURN 0;
  ELSE
    RETURN 1;
  END IF;
END ISMATIERE;
