create or replace
FUNCTION LIST_ATTR(TAB IN VARCHAR2)
                  RETURN VARCHAR2 AS 
  CURSOR ATTRIBUTS(TABNAME USER_TAB_COLUMNS.TABLE_NAME%TYPE) IS SELECT COLUMN_NAME
                                         FROM USER_TAB_COLUMNS
                                         WHERE TABLE_NAME=TABNAME;
  LISTATTR VARCHAR2(255);
  PREM BOOLEAN:=TRUE;
BEGIN
  FOR ATTR IN ATTRIBUTS(TAB) LOOP
    IF NOT PREM THEN
      LISTATTR:=LISTATTR||',';
    END IF;
    PREM:=FALSE;
    
    LISTATTR:=LISTATTR||ATTR.COLUMN_NAME;
  END LOOP;
  RETURN LISTATTR;
END LIST_ATTR;
