-- Question 6
SELECT CODE, MOY_TEST
FROM NOTATION
WHERE NUM_ET = (SELECT NUM_ET
                FROM ETUDIANT
                WHERE NOM_ET = 'ROCCHI'
                AND PRENOM_ET = 'STEPHANE')
ORDER BY MOY_TEST DESC;

SELECT N.MOY_TEST, N.CODE
FROM NOTATION N
JOIN ETUDIANT E ON E.NUM_ET = N.NUM_ET
WHERE E.NOM_ET = 'ROCCHI'
AND E.PRENOM_ET = 'STEPHANE'
ORDER BY MOY_TEST DESC;

-- Question 7
SELECT DISTINCT M.CODE, M.LIBELLE
FROM MODULE M
JOIN ENSEIGNT EN ON M.CODE = EN.CODE
JOIN PROF P ON P.NUM_PROF = EN.NUM_PROF
WHERE NOM_PROF = 'BOITARD'
AND PRENOM_PROF = 'DIDIER';

SELECT DISTINCT M.CODE, M.LIBELLE
FROM MODULE M
JOIN ENSEIGNT EN ON M.CODE = EN.CODE
WHERE NUM_PROF IN (SELECT NUM_PROF
                   FROM PROF
                   WHERE NOM_PROF='BOITARD'
                   AND PRENOM_PROF='DIDIER');
                   
-- Question 8
SELECT DISTINCT GROUPE
FROM ETUDIANT ET
JOIN ENSEIGNT EN ON EN.NUM_ET = ET.NUM_ET
JOIN PROF P ON P.NUM_PROF = EN.NUM_PROF
WHERE NOM_PROF='LAPORTE'
AND PRENOM_PROF='MARC';

SELECT DISTINCT GROUPE
FROM ETUDIANT ET
JOIN ENSEIGNT EN ON EN.NUM_ET = ET.NUM_ET
WHERE EN.NUM_PROF IN (SELECT NUM_PROF
                   FROM PROF
                   WHERE NOM_PROF='LAPORTE'
                   AND PRENOM_PROF='MARC');
                   
-- Question 9
SELECT DISTINCT NOM_ET
FROM ETUDIANT ET
JOIN ENSEIGNT EN ON EN.NUM_ET = ET.NUM_ET
JOIN MODULE M ON M.CODE = EN.CODE
WHERE NUM_PROF IN (SELECT RESP
               FROM MODULE)
ORDER BY NOM_ET;

-- Question 10
SELECT DISTINCT NOM_ET
FROM ETUDIANT ET
JOIN ENSEIGNT EN ON EN.NUM_ET = ET.NUM_ET
JOIN MODULE M ON M.CODE = EN.CODE AND EN.NUM_PROF = M.RESP
ORDER BY NOM_ET;

-- Question 11
SELECT COUNT(*) FROM PROF;

-- Question 12
SELECT AVG(MOY_CC) MOY_MOY_CC
FROM NOTATION
WHERE CODE='PRL';

-- Question 13
SELECT COUNT(DISTINCT NUM_PROF) COUNT_NUM_PROF
FROM ENSEIGNT EN
JOIN ETUDIANT ET ON ET.NUM_ET = EN.NUM_ET
WHERE ET.NOM_ET = 'LYON'
AND ET.PRENOM_ET = 'PHILIPPE';

-- Question 14
SELECT AVG(((NVL(MOY_CC,0)*COEFF_CC)+(NVL(MOY_TEST,0)*COEFF_TEST))/(COEFF_CC+COEFF_TEST)) MOYENNE
FROM MODULE M
JOIN ENSEIGNT EN ON M.CODE = EN.CODE
JOIN ETUDIANT ET ON ET.NUM_ET = EN.NUM_ET
JOIN NOTATION N ON EN.CODE=N.CODE AND EN.NUM_ET=N.NUM_ET
WHERE M.CODE='PRL';

-- Question 15
SELECT MIN(COEFF_TEST) COEFF
FROM MODULE;

-- Question 16
SELECT LIBELLE
FROM MODULE
WHERE COEFF_TEST=(SELECT MIN(COEFF_TEST)
                  FROM MODULE);
                  
-- Question 17
SELECT ROUND(AVG(((NVL(MOY_CC,0)*COEFF_CC)+NVL(MOY_TEST,0)*COEFF_TEST)/(COEFF_CC+COEFF_TEST)),2) MOY
FROM NOTATION N
JOIN ENSEIGNT EN ON N.CODE = EN.CODE
JOIN ETUDIANT ET ON ET.NUM_ET = EN.NUM_ET
JOIN MODULE M ON M.CODE = EN.CODE
WHERE ET.NOM_ET='LEVY'
AND ET.PRENOM_ET='SANDRINE';

-- Question 18
SELECT LIBELLE
FROM MODULE M
JOIN NOTATION N ON M.CODE = N.CODE
WHERE MOY_TEST = (SELECT MAX(MOY_TEST)
                  FROM NOTATION);
                  
-- Question 19
SELECT NOM_ET
FROM ETUDIANT ET
JOIN NOTATION N ON N.NUM_ET = ET.NUM_ET
WHERE MOY_TEST = (SELECT MAX(MOY_TEST)
                  FROM NOTATION);
                  
-- Question 20
SELECT VILLE_ET
FROM ETUDIANT
UNION
SELECT VILLE_PROF
FROM PROF;

-- Question 21
SELECT NUM_PROF, CODE
FROM ENSEIGNT
INTERSECT
SELECT RESP, CODE
FROM MODULE;

-- Question 22
SELECT LIBELLE
FROM MODULE
WHERE CODE IN (SELECT CODE
               FROM MODULE
               MINUS
               SELECT MAT_SPEC
               FROM PROF);
                   
-- Question 23
SELECT DISTINCT RESP, M.CODE
FROM MODULE M
JOIN ENSEIGNT EN ON M.RESP=EN.NUM_PROF AND M.CODE=EN.CODE;

-- Question 24
SELECT LIBELLE
FROM MODULE
WHERE RESP IS NULL
AND CODE NOT IN (SELECT NVL(CODEPERE,0)
                 FROM MODULE);
                 
-- Question 25
SELECT NOM_ET, PRENOM_ET
FROM ETUDIANT ET
WHERE NUM_ET NOT IN (SELECT NUM_ET
                     FROM NOTATION);
                     
SELECT NOM_ET, PRENOM_ET
FROM ETUDIANT ET
WHERE NOT EXISTS (SELECT CODE
                  FROM NOTATION
                  WHERE NUM_ET=ET.NUM_ET);
                  
-- Question 26
SELECT NOM_ET, PRENOM_ET
FROM ETUDIANT ET
WHERE NUM_ET NOT IN (SELECT NUM_ET
                     FROM ENSEIGNT EN
                     JOIN PROF P ON EN.NUM_PROF=P.NUM_PROF
                     WHERE P.NOM_PROF='LAPORTE'
                     AND P.PRENOM_PROF='MARC');
                     
SELECT NOM_ET, PRENOM_ET
FROM ETUDIANT ET
WHERE NOT EXISTS (SELECT NUM_ET
                  FROM ENSEIGNT EN
                  JOIN PROF P ON EN.NUM_PROF=P.NUM_PROF
                  WHERE P.NOM_PROF='LAPORTE'
                  AND P.PRENOM_PROF='MARC'
                  AND EN.NUM_ET=ET.NUM_ET);

SELECT NOM_ET, PRENOM_ET
FROM ETUDIANT E, (SELECT NUM_ET
                FROM ENSEIGNT EN, PROF P
                WHERE EN.NUM_PROF=P.NUM_PROF
                AND NOM_PROF='LAPORTE'
                AND PRENOM_PROF='MARC') MARC
WHERE E.NUM_ET=MARC.NUM_ET(+)
AND MARC.NUM_ET IS NULL;
                  
-- Question 27
SELECT NOM_PROF, PRENOM_PROF
FROM PROF
WHERE NUM_PROF NOT IN (SELECT NVL(RESP,0)
                       FROM MODULE);
                       
SELECT NOM_PROF, PRENOM_PROF
FROM PROF P
WHERE NOT EXISTS (SELECT RESP
                  FROM MODULE
                  WHERE RESP=P.NUM_PROF);
